---
# tasks file for roles/apache
 - name: install apache2
   apt: 
     name=apache2 
     update_cache=yes 
     state=latest


 - name: install php
   apt: 
     name:      
       - apache2
       - libapache2-mod-php 


 
#  - name: download composer installer
#      get_url:
#        url: https://getcomposer.org/installer
#      dest: /tmp/composer

#  - name: install composer
#      shell: php /tmp/composer --install-dir=/usr/local/bin
#      become: yes
