---
# tasks file for roles/nonpass
 - name: extract maven
   ansible.builtin.yum:
     name:
       - unzip
       - tar
     state: latest

 - name: extract archive
   ansible.builtin.unarchive:
     src: "https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz"
     dest: "/opt/"
     remote_src: yes
     validate_certs: yes


 - name: Update path for maven use
   lineinfile:
     dest: /root/.bashrc
     line: 'export PATH=$PATH:/opt/apache-maven-3.8.6/bin'
     insertafter: 'EOF'
     regexp: 'export PATH=\$PATH:/opt/apache-maven-3.8.6/bin'
     state: present   


