---
# tasks file for roles/tomcat
  - name: Update apt packages
    apt:
    #  upgrade: true
      update_cache: true

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: install java
    apt:
      name: openjdk-11-jdk
      state: present
  
  - name: create file tomcat service
    file:
      path: /etc/systemd/system/tomcat.service
      state: touch  
      modification_time: preserve
      access_time: preserve

  - name: Add config to directory /etc/systemd/system/tomcat.service
    ansible.builtin.blockinfile:
      dest: /etc/systemd/system/tomcat.service
      state: present
      
      block: |
          [Unit]
          Description=Tomcat9
          After=network.target
          [Service]
          Type=forking
          Environment=CATALINA_PID=/opt/tomcat/tomcat9.pid
          #Environment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
          Environment=CATALINA_HOME=/opt/tomcat
          Environment=CATALINA_BASE=/opt/tomcat
          Environment="CATALINA_OPTS=-Xms512m -Xmx512m"    # optional
          Environment="JAVA_OPTS=-Dfile.encoding=UTF-8"    # optional
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          [Install]
          WantedBy=multi-user.target

  - name: Make sure a service is running
    ansible.builtin.systemd:
      state: started
      enabled: true
      name: tomcat.service

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true
 
 
